server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.235.118.218:3306/shop?useSSL=false&characterEncoding=UTF-8
    username: root
    password: Root_12root
  rabbitmq:
    host: 49.235.118.218
    port: 5672
    username: walker
    password: walker
    virtual-host: boot_rabbitmq

mybatis:
  type-aliases-package: com.imooc.entity
  mapper-locations: classpath:**/*.xml
logging:
  level:
    com:
      imooc:
        dao: DEBUG